project_id = "nvghinitrmogshcsluys"

[functions.energy-tariff]
verify_jwt = false

[functions.margin-suggestion]
verify_jwt = false

[functions.greenn-webhook]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[functions.migrate-helper]
verify_jwt = false
